services:
    glavweb_datagrid.native_factory:
        class: Glavweb\DatagridBundle\Factory\NativeDatagridFactory
        public: true
        arguments:
            - "@doctrine"
            - "@glavweb_data_schema.data_schema_factory"
            - "@glavweb_datagrid.doctrine_native_filter_factory"
            - "@glavweb_datagrid.native_query_builder_factory"

    glavweb_datagrid.orm_factory:
        class: Glavweb\DatagridBundle\Factory\ORMDatagridFactory
        public: true
        arguments:
            - "@doctrine"
            - "@glavweb_data_schema.data_schema_factory"
            - "@glavweb_datagrid.doctrine_filter_factory"
            - "@glavweb_datagrid.query_builder_factory"

    glavweb_datagrid.doctrine_filter_factory:
        class: Glavweb\DatagridBundle\Filter\Doctrine\ORM\FilterFactory
        arguments: ["@doctrine"]

    glavweb_datagrid.doctrine_native_filter_factory:
        class: Glavweb\DatagridBundle\Filter\Doctrine\Native\FilterFactory
        arguments: ["@doctrine"]

    glavweb_datagrid.query_builder_factory:
        class:  Glavweb\DatagridBundle\Builder\Doctrine\ORM\QueryBuilderFactory
        arguments: ["@doctrine"]

    glavweb_datagrid.native_query_builder_factory:
        class:  Glavweb\DatagridBundle\Builder\Doctrine\Native\QueryBuilderFactory
        arguments: ["@doctrine"]
